# Generated by Django 2.2.7 on 2019-12-01 21:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AmiLaunchIndex', models.IntegerField()),
                ('ImageId', models.CharField(max_length=50)),
                ('InstanceId', models.CharField(max_length=50)),
                ('InstanceType', models.CharField(max_length=50)),
                ('KeyName', models.CharField(max_length=50)),
                ('LaunchTime', models.DateTimeField()),
                ('Monitoring', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
